// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Particle: typeof import('./src/components/Particle.vue')['default']
    Star: typeof import('./src/components/Star.vue')['default']
  }
}

export { }
